version: '3.8'  # Docker Compose file version

services:
  web:  # Defines a service named "web"
    build: .  # Build Docker image from Dockerfile in current directory
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    env_file:
      - .env  # Load environment variables from the .env file
    volumes:
      - .:/app  # Mount current directory (host) to /app in container (for live code updates)
    depends_on:
      - db  # Ensure the db service starts before web
    command: python app.py  # Command to run inside the container

  db:  # Defines a service named "db"
    image: postgres:13  # Use official Postgres image version 13
    environment:
      POSTGRES_USER: user  # Username for Postgres
      POSTGRES_PASSWORD: password  # Password for Postgres
      POSTGRES_DB: mydatabase  # Database name
    ports:
      - "5432:5432"  # Expose database port (optional)
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data on host

volumes:
  pgdata:  # Define named volume for persistent Postgres data
